# Generated by Django 6.0.7 on 2026-09-30 16:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='auto_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProctorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tab_switch', 'Left the exam tab'), ('window_blur', 'Exam window lost focus')], max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_events', to='exams.examattempt')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
    ]
