# Generated by Django 6.0.6 on 2026-10-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examattempt_auto_submitted_proctorevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswer',
            name='grading_method',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='similarity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
