# Generated by Django 6.0.6 on 2026-10-04 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examanswer_grading_method_examanswer_similarity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='max_violations',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='questions_per_student',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='require_fullscreen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='shuffle_options',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='original_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='question_order',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='session_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='submit_reason',
            field=models.CharField(blank=True, choices=[('student', 'Submitted by the student'), ('time', 'Time ran out'), ('violations', 'Too many proctoring violations'), ('closed', 'Exam closed by the instructor')], max_length=20),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='proctorevent',
            name='event_type',
            field=models.CharField(choices=[('tab_switch', 'Left the exam tab'), ('window_blur', 'Exam window lost focus'), ('fullscreen_exit', 'Left fullscreen'), ('copy_paste', 'Tried to copy or paste'), ('new_session', 'Exam opened in another tab or device')], max_length=20),
        ),
    ]
