import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { CheckCircle2, FlaskConical, MinusCircle, RotateCcw, Send, Sparkles, XCircle } from 'lucide-react'
import { api } from '../api/client.js'
import { Alert, EmptyState, PageHeader, ScoreRing } from '../components/ui.jsx'
import { errorText, fmtRelative } from '../utils/format.js'

const POLL_MS = 2000
const KEYS = 'ABCDEFGHIJ'

// Self-tests generated by the T5 pipeline from course material. Never graded.
export default function Practice() {
  const [params, setParams] = useSearchParams()
  const [materials, setMaterials] = useState([])
  const [history, setHistory] = useState([])
  const [form, setForm] = useState({ source: 'material', material: params.get('material') || '', source_text: '',
    question_type: 'mixed', count: 8, quality: 'fast' })
  const [job, setJob] = useState(null)
  const [answers, setAnswers] = useState({})
  const [result, setResult] = useState(null)
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  const sessionId = params.get('session')

  const loadHistory = () => api.get('/ai/practice/', { params: { page_size: 8 } }).then((r) => setHistory(r.data.results ?? r.data))
  useEffect(() => {
    api.get('/courses/materials/').then((r) => setMaterials(r.data.results ?? r.data))
    loadHistory()
  }, [])

  useEffect(() => {
    if (!sessionId) { setJob(null); return undefined }
    let cancelled = false
    let timer
    const fetchJob = () => api.get(`/ai/practice/${sessionId}/`).then((r) => {
      if (cancelled) return
      setJob(r.data)
      setResult(r.data.practice_result)
      if (r.data.status === 'pending' || r.data.status === 'running') timer = setTimeout(fetchJob, POLL_MS)
      else loadHistory()
    }).catch((err) => setError(errorText(err)))
    setAnswers({})
    fetchJob()
    return () => { cancelled = true; clearTimeout(timer) }
  }, [sessionId])

  async function create(e) {
    e.preventDefault()
    setError('')
    setBusy(true)
    const payload = { question_type: form.question_type, count: Number(form.count), quality: form.quality }
    if (form.source === 'material') payload.material = form.material || null
    else payload.source_text = form.source_text
    try {
      const { data } = await api.post('/ai/practice/', payload)
      setParams({ session: String(data.id) })
    } catch (err) {
      setError(errorText(err, 'Could not create the practice test.'))
    } finally {
      setBusy(false)
    }
  }

  async function check() {
    const payload = job.questions.map((q) => ({ index: q.index, ...(answers[q.index] || {}) }))
    try {
      const { data } = await api.post(`/ai/practice/${job.id}/check/`, { answers: payload })
      setResult(data)
      window.scrollTo({ top: 0, behavior: 'smooth' })
    } catch (err) {
      setError(errorText(err))
    }
  }

  const running = job && ['pending', 'running'].includes(job.status)
  const set = (k) => (e) => setForm({ ...form, [k]: e.target.value })

  return (
    <div>
      <PageHeader icon={FlaskConical} title="AI practice"
                  subtitle="Generate a self-test from your course material. Practice tests are for learning only and never count towards results."
                  actions={sessionId && <button className="btn-ghost" onClick={() => setParams({})}><Sparkles size={16} /> New practice test</button>} />
      {error && <Alert type="error" className="mb">{error}</Alert>}

      {!sessionId && (
        <div className="panel-row wide-left">
          <section className="panel">
            <h2>Create a practice test</h2>
            <form className="stack" onSubmit={create}>
              <div className="segmented" style={{ alignSelf: 'flex-start' }}>
                <button type="button" className={form.source === 'material' ? 'active' : ''} onClick={() => setForm({ ...form, source: 'material' })}>From course material</button>
                <button type="button" className={form.source === 'text' ? 'active' : ''} onClick={() => setForm({ ...form, source: 'text' })}>From my notes</button>
              </div>
              {form.source === 'material' ? (
                <label>Course material
                  <select value={form.material} onChange={set('material')} required>
                    <option value="">Choose a file…</option>
                    {materials.map((m) => <option key={m.id} value={m.id}>{m.course_code} — {m.title}</option>)}
                  </select>
                </label>
              ) : (
                <label>Your notes
                  <textarea rows={8} value={form.source_text} onChange={set('source_text')} required
                            placeholder="Paste a paragraph or two of notes — complete sentences work best." />
                </label>
              )}
              <div className="grid-3">
                <label>Question type
                  <select value={form.question_type} onChange={set('question_type')}>
                    <option value="mixed">Mixed</option><option value="mcq">Multiple choice</option>
                    <option value="true_false">True / False</option><option value="short_answer">Short answer</option>
                  </select>
                </label>
                <label>Questions<input type="number" min="1" max="15" value={form.count} onChange={set('count')} /></label>
                <label>AI model
                  <select value={form.quality} onChange={set('quality')}>
                    <option value="fast">Fast</option><option value="better">Better quality</option>
                  </select>
                </label>
              </div>
              <div><button className="btn-primary" disabled={busy}><Sparkles size={16} /> {busy ? 'Starting…' : 'Generate practice test'}</button></div>
            </form>
          </section>
          <section className="panel">
            <h2>Recent practice</h2>
            {history.length === 0
              ? <EmptyState icon={FlaskConical} title="No practice yet" text="Your practice tests and scores appear here." />
              : (
                <ul className="plain-list">
                  {history.map((h) => (
                    <li key={h.id} className="split-row" style={{ cursor: 'pointer' }} onClick={() => setParams({ session: String(h.id) })}>
                      <span>
                        <strong style={{ fontSize: '0.9rem' }}>{h.material_title || 'My notes'}</strong>
                        <div className="muted small">{h.count} questions · {fmtRelative(h.created_at)}</div>
                      </span>
                      {h.practice_result
                        ? <span className="score-pill">{h.practice_result.percentage}%</span>
                        : <span className="tag tag-grey">{h.status_display}</span>}
                    </li>
                  ))}
                </ul>
              )}
          </section>
        </div>
      )}

      {running && (
        <section className="panel center">
          <div className="spinner" />
          <p><strong>Generating your practice test…</strong></p>
          <p className="muted">The T5 model is reading the material. This takes a few seconds.</p>
        </section>
      )}

      {job?.status === 'failed' && <Alert type="error">{job.error}</Alert>}
      {job?.status === 'done' && job.questions.length === 0 && <Alert type="warn">{job.error || 'No questions could be generated from this text.'}</Alert>}

      {job?.status === 'done' && job.questions.length > 0 && result && (
        <section className="panel">
          <div className="hero-row" style={{ justifyContent: 'flex-start', gap: '2rem' }}>
            <ScoreRing percent={result.percentage} sub={`${result.score} / ${result.total}`} />
            <div>
              <h2 style={{ fontSize: '1.3rem', margin: 0 }}>{result.percentage >= 70 ? 'Great work!' : result.percentage >= 50 ? 'Good effort' : 'Keep practising'}</h2>
              <p className="muted">Review the explanations below — each answer links back to the sentence it came from.</p>
              <button className="btn-soft" style={{ marginTop: 10 }} onClick={() => { setResult(null); setAnswers({}) }}><RotateCcw size={15} /> Try again</button>
            </div>
          </div>
        </section>
      )}

      {job?.status === 'done' && job.questions.length > 0 && (
        <section className="panel">
          <div className="head-row"><h2>{job.material_title || 'Practice test'}</h2><span className="tag tag-purple"><Sparkles size={12} /> {job.engine === 't5' ? 'T5 generated' : 'Auto generated'}</span></div>
          {job.questions.map((q) => {
            const fb = result?.questions?.[q.index]
            const cls = fb ? (fb.is_correct ? 'feedback right' : fb.is_partial ? 'feedback partial' : 'feedback wrong') : ''
            return (
              <div key={q.index} className={`q-card ${cls}`}>
                <div className="q-head"><span>Question {q.index + 1}</span>
                  {fb && (fb.is_correct ? <span className="tag tag-green"><CheckCircle2 size={13} /> Correct</span>
                    : fb.is_partial ? <span className="tag tag-amber"><MinusCircle size={13} /> Close</span>
                      : <span className="tag tag-red"><XCircle size={13} /> Incorrect</span>)}
                </div>
                <div className="q-title">{q.text}</div>
                {q.question_type === 'short_answer' ? (
                  <textarea rows={2} style={{ width: '100%' }} disabled={Boolean(result)} placeholder="Your answer"
                            value={answers[q.index]?.answer_text || ''}
                            onChange={(e) => setAnswers({ ...answers, [q.index]: { answer_text: e.target.value } })} />
                ) : q.options.map((o) => (
                  <label key={o.index} className={`opt-row ${answers[q.index]?.option_index === o.index ? 'chosen' : ''}`}>
                    <input type="radio" className="sr-only" disabled={Boolean(result)} checked={answers[q.index]?.option_index === o.index}
                           onChange={() => setAnswers({ ...answers, [q.index]: { option_index: o.index } })} />
                    <span className="opt-key">{KEYS[o.index]}</span>{o.text}
                  </label>
                ))}
                {fb && (
                  <div style={{ marginTop: 8 }}>
                    {!fb.is_correct && <div className="feedback-line" style={{ color: 'var(--success)' }}>Answer: <strong>{fb.correct_answer}</strong></div>}
                    {fb.similarity != null && <div className="feedback-line muted small">Similarity to the expected answer: {fb.similarity}%</div>}
                    {fb.source_sentence && <div className="muted small source-line">From the material: “{fb.source_sentence}”</div>}
                  </div>
                )}
              </div>
            )
          })}
          {!result && <button className="btn-primary btn-lg" onClick={check}><Send size={16} /> Check my answers</button>}
        </section>
      )}
    </div>
  )
}
