from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models

from src.core.models import TimeStampedModel


class QuestionType(models.TextChoices):
    MCQ = 'mcq', 'Multiple Choice'
    TRUE_FALSE = 'true_false', 'True / False'
    SHORT_ANSWER = 'short_answer', 'Short Answer'


class DifficultyLevel(models.TextChoices):
    # Bloom's Taxonomy-aligned tiers (scope doc, Module 2).
    REMEMBER = 'remember', 'Remember'
    UNDERSTAND = 'understand', 'Understand'
    APPLY = 'apply', 'Apply'
    ANALYZE = 'analyze', 'Analyze'
    EVALUATE = 'evaluate', 'Evaluate'
    CREATE = 'create', 'Create'


class Question(TimeStampedModel):
    """
    A single reusable assessment item in an instructor's question bank
    (scope doc, Module 2). MCQ / True-False options live in QuestionOption;
    short-answer items store the reference answer in `correct_answer_text`.
    """
    course = models.ForeignKey(
        'courses.Course', on_delete=models.CASCADE, related_name='questions',
        null=True, blank=True,
    )
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='questions', limit_choices_to={'role': 'instructor'},
    )

    text = models.TextField(help_text='The question prompt.')
    question_type = models.CharField(max_length=20, choices=QuestionType.choices, default=QuestionType.MCQ)
    difficulty = models.CharField(max_length=20, choices=DifficultyLevel.choices, default=DifficultyLevel.UNDERSTAND)
    subject = models.CharField(max_length=120, blank=True, help_text='Subject / topic domain.')
    marks = models.PositiveIntegerField(default=1)

    # Reference answer for short-answer (T5 semantic grading later) and
    # true/false items ('true'/'false').
    correct_answer_text = models.TextField(blank=True)

    # AI provenance: True when generated by the T5 module (scope doc, Module 3).
    is_ai_generated = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    version = models.PositiveIntegerField(default=1)

    class Meta(TimeStampedModel.Meta):
        indexes = [
            models.Index(fields=['created_by', 'is_active']),
            models.Index(fields=['question_type', 'difficulty']),
        ]

    def __str__(self):
        return (self.text[:60] + '…') if len(self.text) > 60 else self.text

    def clean(self):
        # True/False reference answer must be normalised.
        if self.question_type == QuestionType.TRUE_FALSE and self.correct_answer_text:
            if self.correct_answer_text.strip().lower() not in ('true', 'false'):
                raise ValidationError({'correct_answer_text': "True/False answer must be 'true' or 'false'."})


class QuestionOption(TimeStampedModel):
    """A selectable choice for MCQ / True-False questions."""
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='options')
    text = models.CharField(max_length=500)
    is_correct = models.BooleanField(default=False)
    order = models.PositiveSmallIntegerField(default=0)

    class Meta:
        ordering = ['order', 'id']

    def __str__(self):
        return f'{self.text} ({"correct" if self.is_correct else "incorrect"})'
