# Generated by Django 6.0.6 on 2026-10-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_authevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authevent',
            name='event',
            field=models.CharField(choices=[('register', 'Registered'), ('login', 'Logged in'), ('login_failed', 'Failed login'), ('locked', 'Account temporarily locked'), ('logout', 'Logged out'), ('password_reset_request', 'Password reset requested'), ('password_reset', 'Password reset')], max_length=30),
        ),
    ]
