# Generated by Django 6.0.6 on 2026-10-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='required_keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
