from django.conf import settings
from rest_framework import mixins, status, viewsets
from rest_framework.decorators import action
from rest_framework.response import Response

from src.core.permissions import IsInstructor, IsStudent
from src.services.questionbank.serializers import QuestionSerializer
from . import engine
from .extract import ExtractionError, extract_text
from .models import GenerationJob, JobPurpose, JobStatus
from .serializers import CommitSerializer, GenerationJobSerializer, PracticeSerializer
from .services import expire_stale, start_job

QUESTION_FIELDS = ('text', 'question_type', 'difficulty', 'subject', 'marks', 'correct_answer_text', 'options', 'course')


class _JobViewSet(mixins.CreateModelMixin, mixins.ListModelMixin, mixins.RetrieveModelMixin,
                  mixins.DestroyModelMixin, viewsets.GenericViewSet):
    purpose = JobPurpose.BANK

    def get_queryset(self):
        qs = (GenerationJob.objects.filter(created_by=self.request.user, purpose=self.purpose)
              .select_related('course', 'material'))
        expire_stale(qs)
        return qs

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        data = serializer.validated_data
        if not data['source_text']:
            try:
                text = extract_text(data['material'].file)
            except (ExtractionError, OSError, ValueError) as exc:
                return Response({'material': [str(exc) or 'Could not read that file.']},
                                status=status.HTTP_400_BAD_REQUEST)
            if len(text.split()) < 15:
                return Response({'material': ['No readable text was found in that file.']},
                                status=status.HTTP_400_BAD_REQUEST)
            data['source_text'] = text[:settings.AI_MAX_SOURCE_CHARS]
        job = serializer.save(created_by=request.user, purpose=self.purpose)
        start_job(job)
        job.refresh_from_db()
        return Response(self.get_serializer(job).data, status=status.HTTP_202_ACCEPTED)


class GenerationJobViewSet(_JobViewSet):
    """
    AI question generation (scope doc, Module 3).

    POST   /api/ai/jobs/              {source_text | material, question_type, count, difficulty, quality, course?}
                                      -> 202, generation runs in the background
    GET    /api/ai/jobs/<id>/         poll until status is "done", then review `candidates`
    POST   /api/ai/jobs/<id>/commit/  {questions: [...edited candidates]} -> saved to the bank
    GET    /api/ai/jobs/status/       which engine/models are in use
    """
    serializer_class = GenerationJobSerializer
    permission_classes = [IsInstructor]

    @action(detail=False, methods=['get'], url_path='status')
    def engine_status(self, request):
        return Response(engine.status())

    @action(detail=True, methods=['post'])
    def commit(self, request, pk=None):
        job = self.get_object()
        if job.status != JobStatus.DONE:
            return Response({'detail': 'This job has no questions to save yet.'}, status=status.HTTP_409_CONFLICT)
        body = CommitSerializer(data=request.data)
        body.is_valid(raise_exception=True)

        created, errors = [], []
        for index, item in enumerate(body.validated_data['questions']):
            payload = {k: item[k] for k in QUESTION_FIELDS if k in item}
            payload.setdefault('course', job.course_id)
            payload.setdefault('subject', job.subject)
            serializer = QuestionSerializer(data=payload, context={'request': request})
            if serializer.is_valid():
                question = serializer.save(created_by=request.user, is_ai_generated=True)
                created.append(question.id)
            else:
                errors.append({'index': index, 'errors': serializer.errors})

        if created:
            job.saved_count += len(created)
            job.save(update_fields=['saved_count', 'updated_at'])
        return Response(
            {'created': len(created), 'question_ids': created, 'failed': len(errors), 'errors': errors},
            status=status.HTTP_201_CREATED if created else status.HTTP_400_BAD_REQUEST,
        )


class PracticeViewSet(_JobViewSet):
    """
    Student practice tests generated by the same T5 pipeline from course
    material (or the student's own notes). They never count towards results.

    POST /api/ai/practice/             {material | source_text, question_type, count, quality}
    GET  /api/ai/practice/<id>/        questions without answers (poll while generating)
    POST /api/ai/practice/<id>/check/  {answers: [{index, option_index | answer_text}]} -> feedback
    """
    serializer_class = PracticeSerializer
    permission_classes = [IsStudent]
    purpose = JobPurpose.PRACTICE

    @action(detail=True, methods=['post'])
    def check(self, request, pk=None):
        job = self.get_object()
        if job.status != JobStatus.DONE or not job.candidates:
            return Response({'detail': 'This practice test is not ready yet.'}, status=status.HTTP_409_CONFLICT)
        given = {}
        for item in request.data.get('answers') or []:
            if isinstance(item, dict) and str(item.get('index', '')).isdigit():
                given[int(item['index'])] = item

        feedback, score = [], 0.0
        for i, c in enumerate(job.candidates):
            item = given.get(i, {})
            options = c.get('options') or []
            correct_text = (c['correct_answer_text'] if c['question_type'] == 'short_answer'
                            else next((o['text'] for o in options if o['is_correct']), ''))
            result = {'index': i, 'text': c['text'], 'question_type': c['question_type'],
                      'correct_answer': correct_text, 'source_sentence': c.get('source_sentence', ''),
                      'similarity': None}
            if c['question_type'] == 'short_answer':
                answer = str(item.get('answer_text') or '').strip()
                sim, _method = engine.answer_similarity(correct_text, answer) if answer else (0.0, 'empty')
                result.update(your_answer=answer, similarity=round(sim * 100),
                              is_correct=sim >= settings.SHORT_ANSWER_THRESHOLD,
                              is_partial=settings.SHORT_ANSWER_PARTIAL_THRESHOLD <= sim < settings.SHORT_ANSWER_THRESHOLD)
            else:
                idx = item.get('option_index')
                chosen = options[int(idx)] if str(idx).isdigit() and int(idx) < len(options) else None
                result.update(your_answer=chosen['text'] if chosen else '',
                              is_correct=bool(chosen and chosen['is_correct']), is_partial=False)
            score += 1 if result['is_correct'] else 0.5 if result['is_partial'] else 0
            feedback.append(result)

        practice_result = {
            'score': score, 'total': len(job.candidates),
            'percentage': round(score / len(job.candidates) * 100, 1),
            'questions': feedback,
        }
        job.practice_result = practice_result
        job.save(update_fields=['practice_result', 'updated_at'])
        return Response(practice_result)
