# Generated by Django 6.0.6 on 2026-10-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('exam_published', 'Exam scheduled'), ('exam_reminder', 'Exam reminder'), ('result_published', 'Result published'), ('answers_released', 'Answer key released'), ('announcement', 'Instructor announcement'), ('exam_results_ready', 'Exam results computed'), ('review_needed', 'Answers to review'), ('import_complete', 'Question import finished'), ('ai_generation_complete', 'AI question generation finished'), ('account_activity', 'Account activity')], max_length=30),
        ),
    ]
